import math
import pygame

#ajustes del juego
#RES = WIDTH, HEIGHT = 1600, 900
RES = WIDTH, HEIGHT = 1920, 1080
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 0

PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60
PLAYER_MAX_HEALTH = 100


FLOOR_COLOR = (50, 0, 50)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 50

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

TECLA_ARRIBA = pygame.K_UP
TECLA_ABAJO = pygame.K_DOWN
TECLA_IZQUIERDA = pygame.K_LEFT
TECLA_DERECHA = pygame.K_RIGHT
TECLA_DISPARO = pygame.K_LALT
TECLA_ROTARDERECHA = pygame.K_SPACE
TECLA_ROTARIZQUIERDA = pygame.K_LCTRL
TECLA_INICIO = pygame.K_z
